builds:
  - main: ./cmd/kyodai_go/
    binary: kyodai_go
    goos:
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
